name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: qbhy/piplin:latest
#          platforms: linux/amd64,linux/arm64

      - name: Login to Aliyun Docker Registry
        run: echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Aliyun Docker Registry
        run: |
          docker pull qbhy/piplin:latest
          docker tag qbhy/piplin:latest registry.cn-hangzhou.aliyuncs.com/janguly/piplin:latest
          docker push registry.cn-hangzhou.aliyuncs.com/janguly/piplin:latest